image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/cibase:0.8.1

stages:
  - release

release:
  stage: release
  script:
    - npm install --registry ${NPM_REPO} --sass-binary-site=http://npm.taobao.org/mirrors/node-sass
    - chmod -R 755 node_modules
    - npm run compile
    - echo '//${NPM_REGISTRY}:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish --registry ${NPM_PUBLISH_REGISTRY}
  only:
    refs:
      - master
      - tags
      - /^release-.*$/
      - /^hotfix-.*$/

.auto_devops: &auto_devops |
  http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 10 -w %{http_code} "${CHOERODON_URL}/devops/ci?token=${Token}&type=front"`
  if [ "$http_status_code" != "200" ]; then
    cat .auto_devops.sh
    exit 1
  fi
  source .auto_devops.sh

before_script:
  - *auto_devops
